name: 'modal_dialog'
version: 1.0.0
description: Modal Dialog System
author: Gonzalo Chumillas <gchumillas@email.com>
homepage: https://github.com/soloproyectos-dart/modal-dialog
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bootjack: '>=0.6.5+5 <1.0.0'
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '>=1.0.1 <2.0.0'
  domelement: ">=0.1.0 <1.0.0"
  intl: ">=0.13.0 <1.0.0"
transformers:
- dart_to_js_script_rewriter
